services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_SECRET=dev-secret
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
